### ISSUE TITLE
Update OpenTelemetry to 0.19.0

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#2878]
The v0.19.0 packages were released which fixes a bunch of issues, many of which were impacting us: https://github.com/open-telemetry/opentelemetry-rust/releases/tag/v0.19.0

```[tasklist]
### Tasks
- [x] Do the update and make it compile
- [ ] https://github.com/apollographql/router/issues/3201
- [ ] https://github.com/apollographql/router/issues/1162
- [ ] https://github.com/apollographql/router/issues/2066
- [ ] Add tests to ensure that otel metrics are working correctly
- [ ] Identify if histogram metrics are being processed incorrectly by datadog or otlp exporte
```

**Comment by BrynCooke** [comment]
Blocked on https://github.com/tokio-rs/tracing-opentelemetry/pull/12

**Comment by Geal** [comment]
unblocked: https://crates.io/crates/tracing-opentelemetry/0.19.0

**Comment by o0Ignition0o** [comment]
Reopening the issue since we have to revert the upgrade until they release a patch.
