### ISSUE TITLE
Extensibility based on Tower

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#303]
It has been proposed that we shift our architecture to a [Tower](https://github.com/tower-rs/tower/tree/master/tower) based pipeline to:

1. Support a clean model for extending functionality.
2. Provide us with off the shelf functionality common to proxy type software.
3. Reduce our architectural churn.

The router already uses Tower internally, so moving our existing components to services should be something we can do gradually.

A [mockup to demonstrate how this could look has been created](https://github.com/apollographql/router/tree/tower-layer), but the public facing API need to be developed and we need to prove that Tower is going to work for us.

Execution is split in to phases after which we reevaluate if we need to pivot. After each phase the tasks for the following phase will be converted to tickets.

## Phase 1 (1 week) _(COMPLETED!)_:
- [x] #304 
- [x] #340
- [x] #305

## Phase 2 (1 month) _(NEARLY!)_:
- [x] #336
- [x] #342
  - [x] #343
  - [x] #344 `*`
  - [x] #346
  - [x] #345
  - [x] #417
- [x] #347 `*`
- [x] #381 `*`
- [x] #382 `*`
- [x] #383
- [x] #386
- [x] #389
- [x] #390
- [x] #396
- [x] #401
- [x] #402
  - [x] #406
  - [x] #407
  - [x] #409
- [x] Implement some reusable layers:
  - [x] #130   

> `*` = broken but was working previously

## Phase 3 (After merge)

Note that the following tickets need to be prioritized. They are just a bucket of ideas right now:

- [ ] #400
- [x] #449
- [ ] #438
- [ ] #419 
- [ ] #387 
- [x] #403
- [ ] Implement some reusable layers:
  - [ ] #384 `*` 
  - [ ] #398
- [ ] Implements some plugins
  - [ ] #434
  - [ ] #435
  - [ ] #436
  - [x] #388
  - [x] #399
  - [ ] #431
