### ISSUE TITLE
Switching entirely to Rust validation

### ISSUE THREAD

**Issue by goto-bus-stop** [apollographql/router#4168]
After https://github.com/apollographql/router/issues/4159 / https://github.com/apollographql/router/pull/4161 is running for a while, we want to switch to Rust validation entirely.

One thing to remember is Rust validation has different error messages from JS validation. This can be a breaking change for some users who are relying on the error message to identify certain errors. I'd propose we add stable error codes to help justify the changes for users and to avoid locking in error messages forever. Error codes could be part of apollo-rs

```[tasklist]
### Tasks
- [x] update federation-next to apollo-compiler 1.0.0-beta.9
- [x] update router to apollo-compiler 1.0.0-beta.9
- [ ] https://github.com/apollographql/router/issues/4159
- [x] collect apollo.router.validation metrics for some days to a week depending on usage
- [x] experimental_graphql_validation to default to "new" (rust only, no JS validation)
- [ ] https://github.com/apollographql/router/issues/4223
- [ ] https://github.com/apollographql/router/pull/4551
```

**Comment by Geal** [comment]
closing now, this was fixed by https://github.com/apollographql/router/pull/4551
