### ISSUE TITLE
Studio Uplink integration

### ISSUE THREAD

**Issue by abernix** [apollographql/router#442]
## Requirements

Uplink is the Studio machinery / GraphQL endpoint which provides supergraphs to running Gateways (today).  We need to offer the Studio Uplink behavior in the Router, as well.

> This very plausible builds on as a component of the umbrella #66.

The mechanism for retrieving it should match that of the Apollo Gateway, however, the packaging may be abstracted a bit differently, in particular because we may want to allow a Rover command (e.g., `rover supergraph fetch [graphRef] --uplink` to fetch from Uplink as well (as opposed to fetching from non-Uplink, which it does by default).  Furthermore, it's possible that we want to offer the ability to externalize this from the Router by having it as a sidecar/agent.

Since part of this requires making a GraphQL request — something which Rover does already, one of the constraints **might** be matching the patterns that Rover uses (its GraphQL client, etc.).  This should be investigated

## Subtasks

> Someone should own breaking these down into subtasks.

- [ ] Document existing Studio Uplink behavior from Gateway
- [ ] Design implementation for Studio Uplink in Router 
- [ ] Implement Studio Uplink behavior as Rust Crate
